version: '3.8'

services:
  db:
    container_name: mysql-db
    image: mysql
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sports-erp
    ports:
      - 3306:3306
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
